### PR TITLE
Swift 2.0 support

### PR DESCRIPTION
**Pull request by LeeroyDing**

### CODE REVIEW

**Comment by onevcat** [comment]
Thanks @LeeroyDing ! I guess I can merge it when Swift 2 released.

**Comment by LeeroyDing** [comment]
I'll try to keep the code up-to-date with latest Xcode 7 releases.

**Comment by skyebook** [comment]
@onevcat Swift 2 is released now :)

**Comment by onevcat** [comment]
Thanks for mention it!

**Comment by skyebook** [comment]
And thanks for merging it!

**Pull request merged**
